imdb_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("movie.urls", namespace="movie"))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movie/urls.py
from django.urls import path
from . import views

app_name = "movie"

urlpatterns = [
    path("", views.movies, name="movie"),
    path("<int:_id>/", views.movie_details, name="movie_details"),
    path("category/<str:category>", views.filter_by_category, name="filter_by_category"),
    path("language/<str:language>", views.filter_by_language, name="filter_by_language"),
    
]

movie/models.py
from tabnanny import verbose
from django.db import models
from django.utils.text import slugify
from datetime import datetime
# Create your models here.


CATEGORY_CHOICES = (
    ('action','ACTION'),
    ('drama','DRAMA'),
    ('comedy','COMEDY'),
    ('romance','ROMANCE'),
)

LANGUAGE_CHOICES = (
    ('english' , 'ENGLISH'),
    ('german' , 'GERMAN'),
)

STATUS_CHOICES = (
    ('RA' , 'RECRNTLY ADDED'),
    ('MW' , 'MOST WATCHED'),
    ('TR' , 'TOP RATED'),
)



class Movie(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    image = models.ImageField(upload_to="movies")
    banner = models.ImageField(upload_to='movies_banner')
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=10)
    language = models.CharField(choices=LANGUAGE_CHOICES, max_length=10)
    status = models.CharField(choices=STATUS_CHOICES, max_length=2)
    cast = models.CharField(max_length=100)
    year_of_producation = models.DateField()
    views_count = models.IntegerField(default=0)
    movie_trailer = models.URLField()
    created = models.DateTimeField(default=datetime.now())
    slug = models.SlugField(blank=True, null=True)
    

    def save(self , *args , **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        
        super(Movie , self).save(*args , **kwargs)



    def __str__(self) -> str:
        return self.title



LINK_CHOICES = (
    ('D' , 'DOWNLOAD LINK'),
    ('W' , 'WATCH LINK'),
)


class MovieLinks(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    link_type = models.CharField(choices=LINK_CHOICES, max_length=1)
    link = models.URLField()


    class Meta:
        verbose_name = "Movie Link"
        

    def __str__(self) -> str:
        return self.movie.title

movie/views.py
from django.shortcuts import render
from . models import Movie, MovieLinks
from django.core.paginator import Paginator
from django.db.models import Q
# Create your views here.

def movies(request):
    movies = Movie.objects.all()
    search_result = request.GET.get("q")
    if search_result:
        movies = movies.filter(
            Q(title__icontains=search_result)
        )
    paginator = Paginator(movies, 3)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    return render(request, "movie/movie_list.html", context={
        "page_obj": page_obj
    })


def movie_details(request, _id: int):
    movie = Movie.objects.get(pk=_id)
    movie.views_count += 1
    movie.save()
    links = MovieLinks.objects.filter(movie_id = _id)
    related_movies = Movie.objects.filter(category=movie.category).exclude(pk=_id)
    return render(request, "movie/movie_details.html", context={
        "movie": movie, 
        "links": links,
        "related_movies": related_movies
    })


def filter_by_category(request, category):
    movies = Movie.objects.filter(category=category)
    paginator = Paginator(movies, 3)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    return render(request, "movie/movie_list.html", context={
        "page_obj": page_obj
    })


def filter_by_language(request, language):
    movies = Movie.objects.filter(language=language)
    paginator = Paginator(movies, 3)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    return render(request, "movie/movie_list.html", context={
        "page_obj": page_obj
    })

movie/templates/movie/movie_details.html
{% extends 'base.html' %}



{% block content %}

		<main class="content">
			<div class="single">

				<section class="trailer">
					<h3>Trailer</h3>
					<div class="trailer_frame">
						<iframe width="560" height="315" src="{{movie.movie_trailer}}" frameborder="0" allowfullscreen></iframe>
					</div>
				</section>

				<section class="movie">
					<img src="{{movie.image.url}}">
					<ul>
						<li>{{movie.title}}</li>
						<li>{{movie.description}}</li>
						<li><a href="#">Adventure</a>, <a href="#">Drama</a>, <a href="#">Romance</a></li>
						<li><a href="#">{{movie.cast}}</a></li>
						<li>{{ movie.views_count }} Views</li>
					</ul>
				</section>
				<section class="links">
					<h3>Links</h3>
					<ul class="dlinks">
						<li><a>Download</a></li>
						
                        {% for link in links %}
                            
                            {% if link.link_type == "D" %}
                                <li><a href="{{link.link}}">link{{forloop.counter}}</a></li>
                            {% endif %}
                                
                           
                        {% endfor %}
                            
					</ul>
					<ul class="wlinks">
						<li><a>Watch</a></li>
                        
                        {% for link in links %}
                            
                            {% if link.link_type == "W" %}
                                <li><a href="{{link.link}}">link{{forloop.counter}}</a></li>
                            {% endif %}
                                
                            
                        {% endfor %}
                            
					</ul>
				</section>

				<section class="related">
					<h3>Related movies</h3>
					{% for related_movie in related_movies %}
						<div class="relatemovie">
							<a href="{% url 'movie:movie_details' related_movie.id %}"><img src="{{related_movie.image.url}}"></a>
							<a href="{% url 'movie:movie_details' related_movie.id %}"><span class="relatedname">{{related_movie.title}}</span></a>
						</div>
					{% endfor %}
				</section>


			</div>
		</main>

{% endblock content %}

movie/templates/movie/movie_list.html
{% extends 'base.html' %}



{% block content %}
		<main class="content">
			<section class="centered">
				<div class="movies">
                    {% for movie in page_obj %}
                        <div class="mov">
                            <a href="{% url 'movie:movie_details' movie.id %}">
                                <img src="{{movie.image.url}}">
                                <h2 class="movietitle">{{movie.title}}</h2>
                            </a>
                        </div>
                    {% empty %}
                        <h3 style="color:red;display:flex;justify-content: center;align-items: center;">There Are No Movies In This Category</h3>
                    {% endfor %}    
                        
               

                </div>
                
                {% if page_obj.has_other_pages %}
                    <nav class="pagination">
                        <ul>
                            
                            {% if page_obj.has_previous %}
                                <li><a href="?page={{page_obj.previous_page_number}}">Prev</a></li>
                            {% else %}
                                <li class="disabled"></li>
                            {% endif %}
                                

                            {% for page in page_obj.paginator.page_range %}
                                
                                {% if page_obj.number == page %}
                                    <li><a href="#">{{ page }}</a></li>
                                    
                                {% else %}
                                    <li><a href="?page={{ page }}">{{ page }}</a></li>
                                {% endif %}
                            {% endfor %}
                                
                            
                            {% if page_obj.has_next %}
                                <li><a href="?page={{ page_obj.next_page_number }}">Next</a></li>
                            {% else %}
                                <li class="disabled"></li>
                            {% endif %}
                            
                        </ul>
                    </nav>
                {% endif %}
                    
			</section>

		</main>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>Movies</title>
	<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">

	<!-- Link Swiper's CSS -->
	<link rel="stylesheet" href="{% static 'css/swiper.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/styles.css' %}">

	<script src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
	<script src="{% static 'js/script.js' %}"></script>
	

</head>
<body>
	<div class="wrapper">

		<header class="header">
			<figure class="logo"><a href="/"><img src="{% static 'img/logo.png' %}" alt="Logo"></figure></a>
			<nav class="menu">
				<ul>
					<li><a href="/">Home</a></li>
					<li><a>Genres</a>
						<ul>
							<li><a href="{% url 'movie:filter_by_category' 'action' %}">Action</a></li>
							<li><a href="{% url 'movie:filter_by_category' 'comedy' %}">Comedy</a></li>
							<li><a href="{% url 'movie:filter_by_category' 'drama' %}">Drama</a></li>
							<li><a href="{% url 'movie:filter_by_category' 'romance' %}">Romance</a></li>
						</ul>
					</li>
					<li><a>Language</a>
						<ul>
							<li><a href="{% url 'movie:filter_by_language' 'english' %}">English</a></li>
							<li><a href="{% url 'movie:filter_by_language' 'german' %}">German</a></li>
						</ul>
					</li>
					<li class="mobsearch">
						<form class="mobform" method="GET">
							<input type="text" name="query" value="" class="mobsearchfield" placeholder="Search...">
							<input type="submit" value="" class="mobsearchsubmit">
						</form>
					</li>
				</ul>
			</nav>
			<form class="search" method="GET" action="{% url 'movie:movie' %}">
				<input type="text" name="q" value="{{request.GET.q}}" class="searchfield" placeholder="Search..." style="color: #FFF;">
				<input type="submit" value="" class="searchsubmit">
			</form>

			<div class="toggle"><img src="{% static 'img/menu.svg' %}"></div>
		</header>
		<!-- Swiper -->
		<div class="homeslider">
			<div class="swiper-container">

				<div class="swiper-wrapper">
						<div class="swiper-slide">
								<img src="{{movie.banner.url}}">
							<div class="caption">
								<div class="captioninside">
									<h3 style="color: #FFF; font-weight:bold; margin-bottom: 10px">{{movie.title}}</h3>
									<p style="line-height: 1.6;">{{movie.description}}</p>
									<a href="{% url 'movie:movie_details' movie.id %}" class="playbutton">Play</a>
								</div>
							</div>
						</div>
				</div>
				<!-- Add Pagination -->
				<div class="swiper-pagination"></div>
			</div>
		</div>

        
        {% block content %}
            
        {% endblock content %}
            

		<footer class="footer">
			<div class="copyright"><p>Copyright &copy 2024 udaykiriti sriram dheeraj</p></div>
			<div class="footermenu">
				<ul>
					<li><a href="#">Home</a></li>
					<li><a href="#">Contact</a></li>
					<li><a href="#">Terms and conditions</a></li>
				</ul>
			</div>
			<div class="tags">
				<ul>
					<li>Watch Free Movies Trailers</li>
					<li>Movie Trailers</li>
					<li>English Subtitled Movies Trailers</li>
					<li>Latest Movies Trailers</li>
					<li>New Movies Trailers</li>

				</ul>
			</div>

		</footer>

		<!-- Swiper JS -->
		<script src="{% static 'js/swiper.min.js' %}"></script>

		<!-- Initialize Swiper -->
		<script>
			$(document).ready(function(){


				var swiper = new Swiper('.homeslider > .swiper-container', {
					pagination: '.swiper-pagination',
					paginationClickable: true,
					preventClicks:false,
					preventClicksPropagation:false,
					effect:'fade',
					breakpoints: {
						320: {
							height:200
						},

						480: {
							height:300
						},

						768: {
							height:400
						},
						1024: {
							height:500
						}
					}
				});

				var recentswiper = new Swiper('.recentslider > .swiper-container', {
					nextButton: '.recent-next',
					prevButton: '.recent-prev',
					slidesPerView: 8,
					paginationClickable: true,
					preventClicks:false,
					preventClicksPropagation:false,
					spaceBetween: 10,
					breakpoints: {
						320: {
							slidesPerView: 3,
							spaceBetween: 5
						},

						480: {
							slidesPerView: 3,
							spaceBetween: 5
						},

						768: {
							slidesPerView: 5,
							spaceBetween: 5
						},
						1024: {
							slidesPerView: 6,
							spaceBetween: 10
						}
					}
				});

				var mostswiper = new Swiper('.mostslider > .swiper-container', {
					nextButton: '.most-next',
					prevButton: '.most-prev',
					slidesPerView: 8,
					paginationClickable: true,
					preventClicks:false,
					preventClicksPropagation:false,
					spaceBetween: 10,
					breakpoints: {
						320: {
							slidesPerView: 3,
							spaceBetween: 5
						},

						480: {
							slidesPerView: 3,
							spaceBetween: 5
						},

						768: {
							slidesPerView: 5,
							spaceBetween: 5
						},
						1024: {
							slidesPerView: 6,
							spaceBetween: 10
						}
					}
				});

				var topswiper = new Swiper('.topslider > .swiper-container', {
					nextButton: '.top-next',
					prevButton: '.top-prev',
					slidesPerView: 8,
					paginationClickable: true,
					preventClicks:false,
					preventClicksPropagation:false,
					spaceBetween: 10,
					breakpoints: {
						320: {
							slidesPerView: 3,
							spaceBetween: 5
						},

						480: {
							slidesPerView: 3,
							spaceBetween: 5
						},

						768: {
							slidesPerView: 5,
							spaceBetween: 5
						},
						1024: {
							slidesPerView: 6,
							spaceBetween: 10
						}
					}
				});

			});

			
		</script>


	</div>
</body>
</html>